image: k8r.eu/justjanne/android-sdk:27-27.0.3-26.1.1

variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

cache:
  key: $CI_PROJECT_NAME
  paths:
    - ".m2/"
    - ".gradle/"

before_script:
  - "export ANDROID_HOME=/android-sdk-linux"
  - "export PATH=$PATH:/android-sdk-linux/platform-tools/"
  - "chmod +x ./gradlew"

  - "echo $SIGNING_KEYSTORE | base64 -d > /root/signing.keystore"
  - "echo $SIGNING_PROPERTIES > signing.properties"

stages:
  - "build"
  - "test"

build:
  stage: "build"
  script:
    - "./gradlew assembleRelease"
    - "cp app/build/outputs/apk/release/*.apk ."
    - "cp *.apk QuasselDroidNG-release.apk"
  artifacts:
    paths:
      - "*.apk"

unitTests:
  stage: test
  script:
    - "./gradlew test"
