image: "k8r.eu/justjanne/android-sdk:28-28.0.0-26.1.1"

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - ".gradle/wrapper"
    - ".gradle/caches"

before_script:
  - "export GRADLE_USER_HOME=$(pwd)/.gradle"
  - "export ANDROID_HOME=/android-sdk-linux"
  - "export PATH=$PATH:/android-sdk-linux/platform-tools/"
  - "chmod +x ./gradlew"

  - "echo $SIGNING_KEYSTORE | base64 -d > /root/signing.keystore"
  - "echo $SIGNING_PROPERTIES | base64 -d > signing.properties"

stages:
  - "build"
#  - "test"
  - "deploy-local"
  - "deploy-beta"

build:
  stage: "build"
  script:
    - "./gradlew assembleRelease -x lintRelease -x lintVitalRelease"
    - "cp app/build/outputs/apk/release/*.apk ."
  artifacts:
    paths:
      - "*.apk"

#test:
#  stage: "test"
#  script:
#    - "./gradlew check"

deploy-local:
  stage: "deploy-local"
  image: "k8r.eu/justjanne/docker-s3cmd:latest"
  cache: {}
  only:
    refs:
    - "master"
    variables:
    - "$S3_CONFIG"
  dependencies:
  - "build"
  script:
  - "echo $S3_CONFIG | base64 -d > $HOME/.s3cfg"
  - "export VERSION=$(ls *.apk)"
  - "s3cmd put $VERSION s3://releases/quasseldroid-ng/$VERSION"
  - "s3cmd cp s3://releases/quasseldroid-ng/$VERSION s3://releases/quasseldroid-ng/Quasseldroid-latest.apk"

deploy-beta:
  stage: "deploy-beta"
  image: "k8r.eu/justjanne/docker-fastlane:latest"
  cache: {}
  only:
    refs:
    - "master"
    variables:
    - "$FASTLANE_CONFIG"
  dependencies:
  - "build"
  script:
  - "echo $FASTLANE_CONFIG | base64 -d > $HOME/key.json"
  - "export VERSION=$(ls *.apk)"
  - "fastlane supply --apk $VERSION --track beta --json_key $HOME/key.json --package_name com.iskrembilen.quasseldroid"
