image: "k8r.eu/justjanne/android-sdk:30-30.0.3"

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - ".gradle/caches"

before_script:
  - "export GRADLE_USER_HOME=$(pwd)/.gradle"
  - "chmod +x ./gradlew"

  - "echo $SIGNING_KEYSTORE | base64 -d > /root/signing.keystore"
  - "echo $SIGNING_PROPERTIES | base64 -d > signing.properties"

stages:
  - "build"
  - "test"
  - "deploy"

build:
  stage: "build"
  script:
    - "./gradlew assembleRelease -x lintRelease -x lintVitalRelease"
    - "cp app/build/outputs/apk/release/*.apk ."
  artifacts:
    paths:
      - "*.apk"
  except:
    - "tags"

test:
  stage: "test"
  script:
    - "./gradlew check -x connectedCheck"
  artifacts:
    paths:
      - "*/build/test-results/**/TEST-*.xml"
      - "*/build/reports/*.xml"
      - "*/build/reports/cobertura/*.xml"
    reports:
      cobertura:
        - "*/build/reports/cobertura/*.xml"
      junit:
        - "*/build/test-results/**/TEST-*.xml"
        - "*/build/reports/*.xml"
  except:
    - "tags"

deploy-local:
  stage: "deploy"
  image: "k8r.eu/justjanne/docker-s3cmd:latest"
  cache: { }
  only:
    refs:
      - "master"
    variables:
      - "$S3_CONFIG"
  except:
    - "tags"
  dependencies:
    - "build"
  script:
    - "echo $S3_CONFIG | base64 -d > $HOME/.s3cfg"
    - "export VERSION=$(ls *.apk)"
    - "s3cmd put $VERSION s3://releases/quasseldroid-ng/$VERSION"
    - "s3cmd cp s3://releases/quasseldroid-ng/$VERSION s3://releases/quasseldroid-ng/Quasseldroid-latest.apk"

deploy-beta:
  stage: "deploy"
  image: "k8r.eu/justjanne/docker-fastlane:latest"
  cache: { }
  only:
    refs:
      - "master"
    variables:
      - "$FASTLANE_CONFIG"
  except:
    - "tags"
  dependencies:
    - "build"
  script:
    - "echo $FASTLANE_CONFIG | base64 -d > $HOME/key.json"
    - "export VERSION=$(ls *.apk)"
    - "fastlane supply --apk $VERSION --track beta --json_key $HOME/key.json --package_name com.iskrembilen.quasseldroid --skip_upload_metadata=true --skip_upload_images=true --skip_upload_screenshots=true"
